namespace CppWinui
{
    [bindable]
    [default_interface]
	runtimeclass MainWindowViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindowViewModel();
        Int32 MyProperty;
    }
}
